cottagesite/cottagesite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('dashboard.urls', namespace="dashboard")),
    path('admin/', admin.site.urls)
]

cottagesite/dashboard/urls.py
from django.contrib.auth import views as auth_views
from django.urls import include,path

from . import views

app_name = 'dashboard'
urlpatterns = [
        path('', views.index, name='index'),
        path('form/', views.activation_create_view, name='activation_form'),
        path('accounts/', include('django.contrib.auth.urls'))
]

cottagesite/dashboard/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone


class Outlet(models.Model):
    outlet_number = models.IntegerField(blank=False)
    description = models.CharField(default='Outlet object', max_length=200)

    def __str__(self):
        return str(self.outlet_number)
    
class Activation(models.Model):
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    outlet = models.ManyToManyField(Outlet)
    activation_time = models.DateTimeField(blank=False)
    deactivation_time = models.DateTimeField(blank=False)

    def __str__(self):
        return str(self.activation_time)

    def is_active(self):
        return self.activation_time < timezone.now() and \
                self.deactivation_time > timezone.now()

    def is_in_future(self):
        return self.activation_time > timezone.now()

# Create your models here.

cottagesite/websocketControl/models.py
from django.db import models

class Client(models.Model):
    client_types = [('CTRL', 'control')]
    channel_name = models.CharField(blank=False, max_length=100)
    channel_type = models.CharField(blank=False, max_length=100, 
                                    choices=client_types)

    def __str__(self):
        return str(self.channel_name)

cottagesite/dashboard/forms.py
from django import forms


from .models import Activation, Outlet


class ActivationForm(forms.ModelForm):
    outlet = forms.ModelMultipleChoiceField(
        queryset=Outlet.objects.all(),
        widget=forms.CheckboxSelectMultiple(attrs={
                'class': 'required form-check form-control'}))

    class Meta:
        model = Activation
        exclude = ['owner']

cottagesite/dashboard/views.py
from asgiref.sync import async_to_sync

from django.contrib import auth
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render
from django.http import HttpResponseForbidden
from django.views.generic import ListView, FormView
from django.views.generic.edit import FormView
from django.views.generic.detail import SingleObjectMixin
from django.urls import reverse
from django.utils import timezone

from channels.layers import get_channel_layer
import json
import datetime

from .forms import ActivationForm
from .models import Activation, Outlet
from websocketControl.models import Client

@login_required
def activation_create_view(request):
    form = ActivationForm(request.POST or None) 
    if form.is_valid():
        activation = form.save(commit=False)
        activation.owner = request.user
        activation.save()
             
        data = form.cleaned_data
        channel_layer = get_channel_layer()
        
        outlet_data = {}
        for outlet in data['outlet']:
            activation.outlet.add(outlet)
            outlet_data[str(outlet)] = {
                'activation_time': data['activation_time'].timestamp(),
                'deactivation_time': data['deactivation_time'].timestamp()
            }
        
        message = {
            'type': 'chat.message',         # For django_redis
            'request': {
                'recipient': 'outlet_control',
                'sender': 'web-server',
                'request_type': 'ACTIVATION',
                'outlet_data': outlet_data
            }
        }

        async_to_sync(channel_layer.group_send)('CONTROLGROUP', message)

    context = { 'form': form }
    
    return render(request, 'dashboard/activation_create.html', context)
    

@login_required
def index(request):
    outlets = Outlet.objects.all()
    activations  = Activation.objects.filter(
        deactivation_time__gt=datetime.datetime.now()). \
            order_by('deactivation_time').order_by('activation_time')[:10]

    return render(request, 'dashboard/index.html', 
            {'outlets' : outlets, 'activations' : activations})

cottagesite/dashboard/templates/base.html
<!DOCTYPE html>
<html>
    <head>
        <title>Dashboard for managing outlets at the summer cottage </title>
            <meta charset="utf-8">
            <meta name="viewport" content="width=device-width, initial-scale=1">
          
            {# Include FontAwesome; required for icon display #}
            <link rel="stylesheet" href="https://netdna.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.css">
            <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
            <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
            <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.22.2/moment.min.js"></script>
            <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
            
            {% if form %}
            <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/tempusdominus-bootstrap-4/5.0.1/js/tempusdominus-bootstrap-4.min.js"></script>
            <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/tempusdominus-bootstrap-4/5.0.1/css/tempusdominus-bootstrap-4.min.css" />       
            {% endif %}

          </head>
    <body>

        {% include 'dashboard/navbar.html' %}

        <div class='jumbotron'>
        {% block content %} {% endblock %}
        </div>
    </body>
</html>

cottagesite/dashboard/templates/dashboard/activation_create.html
{% extends 'base.html' %}

{% block content %}

<div class="container">
    <div class="row justify-content-md-center">
        <div class="form-group" id="activation-create-form">
            <form action="" method="POST" accept_charset="utf-8">
                {% csrf_token %}
                {{ form.non_field_errors }}
                
                <p><div class="bg-secondary text-white h4">Outlets:</div>
                <div class="input-group" id="outlets">
                    
                    {% for outlet in form.outlet %}
                        {{ form.outlet.errors }}
                        <div class="form-check form-check-inline">
                        {{ outlet }}
                        </div>
                    {% endfor%}
                </div></p>
                <p><div class="bg-secondary text-white h4">Activation Time:</div>
                <div class="input-group date" id="activation_time_picker" data-target-input="nearest">
                    {{ form.activation_time.errors }}
                    {{ form.activation_time }}
                    <div class="input-group-append" data-target="#activation_time_picker" data-toggle="datetimepicker">
                        <div class="input-group-text"><i class="fa fa-calendar"></i></div>
                    </div>
                </div></p>
                <p><div class="bg-secondary text-white h4">Deactivation Time:</div>
                <div class="input-group date" id="deactivation_time_picker" data-target-input="nearest">
                    {{ form.deactivation_time.errors }}
                    {{ form.deactivation_time }}
                    <div class="input-group-append" data-target="#deactivation_time_picker" data-toggle="datetimepicker">
                        <div class="input-group-text"><i class="fa fa-calendar"></i></div>
                    </div>
                </div></p>
                <input id="activation-create-submit" type="submit" value="Save">
                <p id="activation-create-finished"></p>
            </form>
        </div>
    </div>
</div>

<script type="text/javascript">

    $(document).ready(function() {
        $('#id_activation_time').attr({
            "class": "form-control datetimepicker-input",
            "data-target": "#activation_time_picker"
        });
        $('#id_deactivation_time').attr({
            "class": "form-control datetimepicker-input",
            "data-target": "#deactivation_time_picker"
        });
    });

    $(function () {
        $('#activation_time_picker').datetimepicker({
            format: "YYYY-MM-DD HH:mm"
        });

        $('#deactivation_time_picker').datetimepicker({
            format: "YYYY-MM-DD HH:mm"
        });

        $('#activation_time_picker').on("change.datetimepicker", function (e) {
            $('#deactivation_time_picker').datetimepicker('minDate', e.date);
        });
        
        $('#deactivation_time_picker').on("change.datetimepicker", function (e) {
            $('#activation_time_picker').datetimepicker('maxDate', e.date);
        });
    });

</script>
<script type="text/javascript">
    $(document).ready(function() {
        $('#outlets').find('option').unwrap();
    });
</script>

{% endblock %}

cottagesite/dashboard/templates/dashboard/base.html
<!DOCTYPE html>
<html>
    <head>
        <title>Dashboard for managing outlets at the summer cottage </title>
          <meta charset="utf-8">
          <meta name="viewport" content="width=device-width, initial-scale=1">
          <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
          <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
          <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
          <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
         <!-- <link rel="stylesheet" type="text/css" href="/static/admin/css/forms.css"/>
          <link rel="stylesheet" type="text/css" href="/static/admin/css/base.css"/>
          <link rel="stylesheet" type="text/css" href="/static/admin/css/global.css"/>
          <link rel="stylesheet" type="text/css" href="/static/admin/css/widgets.css"/>
         -->
          </head>
    <body>
        <!--
        <script type="text/javascript" src="/admin/jsi18n/"></script>
        <script type="text/javascript" src="/static/admin/js/core.js"></script>
        <script type="text/javascript" src="/static/admin/js/admin/RelatedObjectLookups.js"></script>
        <script type="text/javascript" src="/static/admin/js/jquery.init.js"></script>
        <script type="text/javascript" src="/static/admin/js/actions.js"></script>
        <script type="text/javascript" src="/static/admin/js/calendar.js"></script>
        <script type="text/javascript" src="/static/admin/js/admin/DateTimeShortcuts.js"></script>
        -->
        {% include 'dashboard/navbar.html' %}

        <div class='jumbotron'>
        {% block content %} {% endblock %}
        </div>

    </body>
</html>

cottagesite/dashboard/templates/dashboard/index.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <div class="row">
        {% for outlet in outlets %}
        <div class="col">
            <h1 class="outlet_status_title">{{ outlet.id }}</h1> 
            <h2 id="outlet-status-{{ outlet.id }}" class="text-danger">Inactive</h2>
        </div>
        {% endfor %}
    </div>
</div>

    <!---Turn this to be done entirely on browsers, i.e. no django funcs-->
    <script type="text/javascript">
        {% for activation in activations %}
        if ('{{ activation.is_active }}' === 'True') {
            {% for outlet in activation.outlet.all %}
                var s = $('#outlet-status-{{ outlet.id }}');
                s.removeClass('text-danger').addClass('text-success');
                console.log(s);
                s.text('Active');
            {% endfor %}
        }
        {% endfor %}
    </script>        

<div class="container">
    <div class="row">
      <div class="col">            
          <table class="table">
            <thead class="thead-dark">
                <tr>
                    <th>Owner</th>
                    <th>Outlet</th>
                    <th>Activation Time</th>
                    <th>Deactivation Time</th>
                </tr>
            </thead>
            <tbody>
                {% for activation in activations %}  
                <tr>
                    <td>{{ activation.owner }}</td>
                    <td>
                        {% for outlet in activation.outlet.all %}
                        {{ outlet }} {% if not forloop.last %}, {% endif %}
                        {% endfor %}
                    </td>
                    <td>{{ activation.activation_time }}</td>
                    <td>{{ activation.deactivation_time }}</td>
                </tr>
                {% endfor %}
            </tbody>
          </table>
      </div>
    </div>
</div>
{% endblock %}

cottagesite/dashboard/templates/dashboard/navbar.html
<ul class="nav justify-content-center">
    {% if user.is_authenticated %}
    <li class="nav-item">
        <a class="nav-link" href="{% url 'dashboard:index' %}">Home</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" href="{% url 'dashboard:activation_form' %}">Activate Outlet</a>
    </li>
    {% comment %}
    <li class="nav-item">
        <a class="nav-link" href="{% url 'dashboard:logout' %}?next=/">Logout</a>
    </li>
    {% else %}
    <li class="nav-item">
        <a class="nav-link" href="{% url 'dashboard:login' %}">Login</a>
    </li>
    {% endcomment %}
    {% endif %}
</ul>

cottagesite/dashboard/templates/dashboard/table.html
<table class="table">
    <thead class="thead-dark">

      <tr>
        <th>Firstname</th>
        <th>Lastname</th>
        <th>Email</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td>John</td>
        <td>Doe</td>
        <td>john@example.com</td>
      </tr>
      <tr>
        <td>Mary</td>
        <td>Moe</td>
        <td>mary@example.com</td>
      </tr>
      <tr>
        <td>July</td>
        <td>Dooley</td>
        <td>july@example.com</td>
      </tr>
    </tbody>
  </table>